spring.application.name=payment-api
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payments_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#
mpesa.consumer-key=YOUR_KEY
mpesa.consumer-secret=YOUR_SECRET
mpesa.service-provider-code=171717