spring.application.name=payment-api
server.port=${SERVER_PORT:8080}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payments_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# M-Pesa
mpesa.consumer-key=${MPESA_CONSUMER_KEY:mock}
mpesa.consumer-secret=${MPESA_CONSUMER_SECRET:mock}
mpesa.service-provider-code=${MPESA_SERVICE_PROVIDER_CODE:171717}